### ISSUE TITLE
Missing Pattern

### ISSUE THREAD

**Issue by nunobrum** [nunobrum/spicelib#108]
Hello, Nuno.

I and my friend prepare the files of example(21parameter opamp, below link).

But error happen and 
the message seems to point that format of .net file is not properly.
We checked the net file, but we couldn't find any mistake.
[The part of error message]
   Expected pattern "^\* " not found in file [absolute_path]/amp3.net

Please give a glance the errorMessage and net-file.
    (net-file(named amp3.net) is in SourceCase, also control-python file is attached, calling SpiceEditor on line115)

https://asco.sourceforge.net/examples.html

[SourceCase.zip](https://github.com/user-attachments/files/17282791/SourceCase.zip)

```
Traceback (most recent call last):
  File "/home/touhu/Project/CMOS/target.py", line 115, in <module>
    netlist = SpiceEditor(currDir + "/amp3.net")
  File "/home/touhu/.local/lib/python3.10/site-packages/spicelib/editor/spice_editor.py", line 944, in _init_
    raise err
  File "/home/touhu/.local/lib/python3.10/site-packages/spicelib/editor/spice_editor.py", line 942, in _init_
    self.encoding = detect_encoding(self.netlist_file, r'^\* ')  # Normally the file will start with a '*'
  File "/home/touhu/.local/lib/python3.10/site-packages/spicelib/utils/detect_encoding.py", line 77, in detect_encoding
    raise EncodingDetectError(f"Expected pattern \"{expected_pattern}\" not found in file:{file_path}")
spicelib.utils.detect_encoding.EncodingDetectError: Expected pattern "^\* " not found in file:/home/touhu/Project/CMOS/div2_1111111111111111111111111111111111111/amp3.net
```

**Comment by nunobrum** [comment]
Dear Sir,

SpiceEditor is expecting that the first line be a comment. It is so for legacy reasons. Typically LTSpice generated netlists that started with the name of the schematic that originated it.
![image](https://github.com/user-attachments/assets/98b9bc07-f0e1-4592-94a5-24c0cec6dba1)

You can solve the problem just by adding a first line with a * as a first character
